import Link from "next/link";
import { Metadata } from "next";
import About from "../../component/about";

export const metadata: Metadata = {
  title: "Bono Design | Projects",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png", // hanya satu gambar favicon
  },
};

export default function AboutPage() {
  return (
    <main className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8 py-12 md:py-20">
      <About />
    </main>
  );
}
