import Link from "next/link";
import PortfolioSection from "../../component/porto";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Bono Design | Projects",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png", // hanya satu gambar favicon
  },
};

export default function ProjectsPage() {
  return (
    <main>
      <PortfolioSection />
    </main>
  );
}
