import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../component/navbar";
import Hero2 from "../component/hero-2";
import About from "../component/about";
import Services from "../component/service";
import PortfolioSection from "../component/porto";
import Testimonials from "../component/testimonial";
import Contact from "../component/contact";
import ScrollToTop from "../component/scrollToTop";
import Panorama360 from "../component/parinama360";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Afif Design | Home",
  description: "Generated by create next app",
  icons: {
    icon: "/2.yosemite.jpg", // hanya satu gambar favicon
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased bg-background-light dark:bg-background-dark font-display text-stone-800 dark:text-stone-200">
        <div className="relative flex min-h-screen w-full flex-col overflow-x-hidden">
          {/* Navbar fixed di atas */}
          <Navbar />

          {/* Main content */}
          <main className="flex-1">
            <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8 py-12 md:py-20">
              <Hero2 />
              <About />
              <Services />
              <PortfolioSection />
              <Panorama360 />
              <Testimonials />
              <Contact />
              {/* {children} */}

              {/* Jika ingin children dinamis, uncomment */}
              {/* {children} */}
            </div>

            {/* Scroll to top button */}
            <ScrollToTop />
          </main>

          {/* Footer */}
          <footer className="flex flex-col gap-6 px-5 py-10 text-center">
            <p className="text-stone-500 dark:text-stone-400 text-base">
              © 2024 Afif Designs. All rights reserved.
            </p>
          </footer>
        </div>
      </body>
    </html>
  );
}
