import Image from "next/image";
import About from "../component/about";
import Services from "../component/service";
import PortfolioSection from "../component/porto";
import Testimonials from "../component/testimonial";
import Contact from "../component/contact";
import ScrollToTop from "../component/scrollToTop";
import ExperienceSection from "../component/experiance";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Bono Design | Home",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png", // hanya satu gambar favicon
  },
};

export default function Home() {
  return (
    <>
      <About />
      <Services />
      <ExperienceSection />
      <PortfolioSection />
      {/* <Panorama360 /> */}
      <Testimonials />
      <Contact />
    </>
);
}
